services:
  vivatech_back_api:
    container_name: vivatech_back_api
    image: node:lts
    env_file: ./src/.env
    working_dir: /usr/src/app
    volumes:
      - ./src/api:/usr/src/app
    ports:
      - 3333:3000
    command: npm run watch
    depends_on:
      - vivatech_back_db
    links:
      - vivatech_back_db
    networks:
      - vivatech_back

  vivatech_back_adminer:
    container_name: vivatech_back_adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - vivatech_back_db
    networks:
      - vivatech_back
      
  vivatech_back_db:
    container_name: vivatech_back_db
    image: mariadb:latest
    env_file: ./src/.env
    volumes:
      - ./src/db:/var/lib/mysql
      - ./src/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - vivatech_back

networks:
  vivatech_back:
    driver: bridge